### ISSUE TITLE
I developed a port of coolshapes for Vue.js

### ISSUE THREAD

**Issue by xiaoluoboding** [realvjy/coolshapes-react#9]
I appreciate your great work, @realvjy! I love the cool shapes you created. I built this for the Vue community.

- websites: [https://coolshapes-vue.vercel.app/](https://coolshapes-vue.vercel.app/)
- repo: [https://github.com/xiaoluoboding/coolshapes-vue](https://github.com/xiaoluoboding/coolshapes-vue)

**Comment by realvjy** [comment]
This is really wonderfull. Love it. Thanks for your contribution. ❤️
I'll update it on redme soon.
